# Generated by Django 4.2.4 on 2023-08-14 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'news', 'verbose_name_plural': 'newss'},
        ),
    ]
